metal3-io/ironic-image

Dockerfile
Reflect changes from https://github.com/vrutkovs/dev-scripts/pull/55
=> Support bare metal

Dockerfile
This should fix the image build
@hardys PTAL
=> Install ipxe-bootimgs

Dockerfile
This got lost in the repository move
=> Configure default_deploy_interface=direct

Dockerfile
=> Join several layers, cleanup yum cache

Dockerfile, runironic.sh
Disclaimer: I haven't tested it.
=> Switch to JSON RPC instead of Rabbit MQ

Dockerfile, runhealthcheck.sh, runironic.sh
Add a script that runs inside the container monitoring
the processes that need to be available, if any of them fail then
kill the container. We can then more reliably check the container
status to see if its running or not.
=> Add runhealthcheck.sh

Dockerfile
Allow us to use idrac interfaces on Dell HW.
=> Enable idrac interfaces

Dockerfile, runironic.sh, runmariadb.sh
Splitting mariadb container from ironic
Relates to:
https://github.com/openshift-metalkube/dev-scripts/pull/241
=> Split mariadb and ironic containers

README.md, dnsmasq.conf, rundnsmasq.sh, runhttpd.sh, runironic.sh, runmariadb.sh
Add the ability to configure the containers based on interface
rather than specific IPs.  We don't know the IP address the pod
will be run on so we need a way to do this dynamically.
=> Add more configuration options to containers.

Dockerfile
=> Move to Train branch

Dockerfile
=> Add python-sushy-oem-idrac pkg for vmedia boot interface

configure-ironic.sh
In order to skip automated_cleaning on some development environment
=> Add ironic automated_clean configuration option

Dockerfile
=> Use master for tripleo repo

Dockerfile
Reverts metal3-io/ironic-image#141 due to a bug in ironic upstream :https://storyboard.openstack.org/#!/story/2007622
=> Revert "Use tested packages"

Dockerfile, configure-ironic.sh
Reverts metal3-io/ironic-image#154
Reverts the revert to use the intended packages after ironic inspector bug fix
=> Use tested packages

Dockerfile, ironic.conf
=> Add ibmc driver

configure-ironic.sh, inspector.ipxe, ironic.conf, runhttpd.sh
We should only set power_off to false when fast_track is true.
=> Set power_off = !fast_track in [inspector]

dnsmasq.conf.j2
Fixes https://github.com/metal3-io/ironic-image/issues/203.
=> Revert dhcp-sequential-ip

configure-ironic.sh, ironic.conf.j2, runmariadb.sh
This PR is related to:
https://github.com/metal3-io/metal3-dev-env/pull/525
https://github.com/metal3-io/baremetal-operator/pull/689
This PR needs to be merged before the two PRs above can pass CI tests
=> Make Ironic connect to Mariadb using TLS

OWNERS
I feel like I'm getting pretty familiar with this repo now.
=> Add zaneb as reviewer

Dockerfile, prepare-image.sh
In the effort of cleaning the Dockerfile, we move the upgrade and
install logic to a script.
=> Move upgrade and install logic to a script

ironic.conf.j2
Closes https://github.com/metal3-io/baremetal-operator/issues/461
=> Fix incorrect IPA option (closes baremetal-operator#461)

ironic.conf.j2
To enable development/testing related to https://github.com/metal3-io/metal3-docs/pull/150
=> Enable ramdisk deploy_interface

prepare-image.sh
Also make build process fail if something goes wrong in prepare-image
=> Prevent unbound variable error in prepare-image

main-packages-list.txt, prepare-image.sh
With this change we can specify package versions to be installed
directly in the packages list (main or extra).
=> Allow specify package versions

OWNERS
He's an Ironic core reviewer and has been providing useful reviews
to ironic components in Metal3.
=> OWNERS: Add Iury to reviewers

ironic-config/ironic.conf.j2
Required for https://github.com/metal3-io/metal3-docs/pull/180.
=> Enable the custom-deploy deploy interface

scripts/runlogwatch.sh
Currently it only waits for files in the first created directory because
of an infinite loop inside the "for" loop.
=> Rework runlogwatch.sh

Dockerfile, prepare-image.sh
Move change ownership of /var/log/ironic
Aggregate file removals
Remove file removal duplicate
=> Move RUN commands to prepare-image

ironic-config/apache2-ironic-api.conf.j2, ironic-config/ironic.conf.j2, ironic-inspector-config/inspector-apache.conf.j2, ironic-inspector-config/ironic-inspector.conf.j2, scripts/ironic-common.sh, scripts/runironic-inspector
- Make private proxied ports configurable
- Tell Ironic the correct public endpoint
=> Clean up reverse proxy support

README.md
Airship name from CI jenkins view have been deprecated
=> Update CI badges with Metal3

main-packages-list.txt
Got reintroduced by mistake in 39c5b7d09adc58311b725e9e8efebac0bf6eb1de.
=> Remove unused dependencies - take 2

prepare-efi.sh
=> Add verbose logging to prepare-efi.sh

Dockerfile, prepare-efi.sh
=> Move glibc-conv-extra install into prepare-efi

scripts/ironic-common.sh
See https://bugzilla.redhat.com/show_bug.cgi?id=2081734 for details
=> ignore case of mac address

ironic-inspector-config/inspector-apache.conf.j2
ServerName was hard coded. Not quite sure if we should use IRONIC_IP here or perhaps IRONIC_URL_HOST or something?
=> Inspector: Set server name from variable

OWNERS
Although, community guideline is to have 10 commits for a reviewer, this particular repository doesn't see that much commit on its own. I believe Lennart and Adam has necessary knowledge on this repo and they can be of help while reviewing codes in this repo.
=> Add Lennart and Adam as reviewers

scripts/configure-ironic.sh, scripts/runironic-inspector
Ensure internal ironic traffic bypasses any proxies
=> Add ironic IP to no_proxy

README.md, hack/markdownlint.sh
Add markdownlint. Fix all the markdownlint complaints.
Another PR in project-infra will activate the check for PRs.
This is markdownlint part separated from #412
=> add markdown linter and fix complaints

Dockerfile, README.md, prepare-image.sh
Also fix ironic-lib from source installation
=> Add upper-constraints file customization

ironic-config/ironic.conf.j2
Since there is no nova involved, lets disable the power notifications.
Closes: #444
=> Disable nova power notifications

ironic-config/httpd-ironic-api.conf.j2, ironic-config/ironic.conf.j2, scripts/configure-ironic.sh, scripts/ironic-common.sh, scripts/runhttpd, scripts/runironic-inspector
A lot more clean-up is possible, but this change allows testing
the new approach already.
Requires:
- https://github.com/metal3-io/baremetal-operator/pull/1446
- https://github.com/metal3-io/baremetal-operator/pull/1450
=> Minimum change to support inspection without inspector

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-verifier.yaml
Add pull request template, and a Github workflow to verify the PR contents, like verifying the change type emoji in title. This supports creation of release notes for future releases.
=> :seedling: add pull request template and workflow to verify it

.github/workflows/build-images-action.yml
It is missing stuff and also inconsistent with main.
/hold
Until verified in IPAM first.
=> 🌱 fix build images action in release-23.1

README.md
This PR is updating the build status after changing jenkins jobs naming
=> 🌱 Update build status on release-23.1

Makefile
Introduce variable to set build container engine.
Build with podman by default.
=> :seedling: Update Makefile

patch-image.sh, prepare-image.sh, resources/vbmc/Dockerfile
Also update pip install commands where needed from `pip3` to `pythib3 -m pip`
=> :seedling: Update pip version

prepare-image.sh
Follow up to https://github.com/metal3-io/ironic-image/pull/585
=> 🌱 improve bash syntax in prepare-image

docs/releasing.md
=> 📖 Releasing: add IrSO to post-release actions

scripts/runlogwatch.sh
=> :bug: Fix runlogwatch failure if LOG_DIR does not exist

docs/releasing.md
Adding a reminder to update the supported versions matrix in
the metal3-docs.
=> :seedling: Add change to supported versions in release docs

scripts/runhttpd, scripts/runironic, scripts/tls-common.sh
=> 🌱 Refactoring: add a helper for restarting a service on certificate update

.github/workflows/irso-functional.yml, hack/ci-e2e.sh
* Use minikube instead of kind for the cluster
* Add a JUnit report and annotate failures in the job
=> 🌱 Synchronize the IrSO functional job with IrSO

Dockerfile
Add labels to Dockerfile. `images.version` label will be set by automation during build.
Fix some indentation issues and convert PKGS_LIST to ARG.
Supersedes abandoned PR https://github.com/metal3-io/ironic-image/pull/591
=> :seedling: add labels to dockerfile

resources/ironic-client/Dockerfile, resources/sushy-tools/Dockerfile, resources/vbmc/Dockerfile
Add org.opencontainers labels to three Dockerfiles in resources/.
=> :seedling: add labels to Dockerfiles in resources

README.md
It took me too long to figure out how this was working and what user to use. Hopefully this will spare others from the effort.
Fixes #
=> 📖 Expand docs on ramdisk ssh key

tools/parse-ramdisk-logs.py
=> 🌱 Minor improvements for tools/parse-ramdisk-logs.py

prepare-image.sh
=> :seedling: Install jinja2 and pyinotify constrained

README.md
This has bitten me a couple of times recently so now I want to fix it.
There is no default, and the value should contain comma separated IPs (not <start>-<end> format).
Fixes #
=> 📖 Update DHCP_RANGE description

docs/releasing.md
Update docs/releasing.md on dependabot config changes while releasing new minors.
=> :book: update docs/releasing.md on dependabot configs

releasenotes/v32.0.0.md
=> :rocket: Release v32.0.0
