Dockerfile
We now bind mount it in, so it can be downloaded once
and reused, which should make the image a lot smaller.
=> Stop baking IPA into the image

Dockerfile
In order for ironic to trigger ironic-inspector directly
in a workflow where a machine may be manually added and not
discovered, we need configuration in ironic.conf to both enable
the ``inspector`` interface, as well as point ironic to inspector
to enable it's internal workflow for data collection... outside
of discovery operations.
=> Add ironic-inspector configuration to container

Dockerfile
The default mode does not work well when several threads and/or processes
are reading and writing to the same database. This change switches
to the WAL mode available since sqlite 3.7.0.
The mode is persistent for a file until changed, so we pre-create
the database file when building a container.
=> Switch to using WAL for ironic sqlite database

Dockerfile, rundnsmasq.sh, runhealthcheck.sh, runhttpd.sh, runironic.sh
Allows Ironic container to be split between ironic, dnsmasq, and httpd
containers using this same image.
=> Changes to split up Ironic container

Dockerfile
Until https://review.openstack.org/#/c/648358/ lands master
tripleo-repos is broken
=> Pin tripleo-repos to avoid bug

Dockerfile, runironic.sh
Turns out we need a real database for the level of parallel
access. Changes out the database to an instance of mariadb
that is configured upon start-up if necessary with a random
password and unrelated database rights are removed.
=> Change out sqlite to mariadb

dnsmasq.conf, rundnsmasq.sh
When running dnsmasq on master nodes we don't want to run DHCP
server on a 'production' network with an external DHCP server.
To specify interfaces that have to be excluded specify them as
a comma separated list, for e.g.:
EXCEPT_INTERFACE="lo,em1,enp12s0"
=> Allow to exclude listen interfaces for dnsmasq.

Dockerfile
Ironic 12.1.0 released an awesome feature that allows us
to radically reduce the deployment time by starting the agent
up upon a baremetal node early on and allowing
it to record heartbeat operations.
=> Add fast track to container settings

rundnsmasq.sh, runhttpd.sh
Attempt to run standalone ironic-httpd container fails:
AH00526: Syntax error on line 119 of /etc/httpd/conf/httpd.conf:
DocumentRoot '/var/www/html' is not a directory, or is not readable
/bin/runhttpd: line 18:    12 Killed                 sleep infinity
So it makes sense to prepare httpd's files/dirs within /bin/runhttpd
script rather than in /bin/rundnsmasq.
=> Configure HTTPd related directory within runhttpd.sh

runironic.sh
Testing indicates this is a reasonable maximum, and avoids launching $many
workers on boxes with many CPU cores.
This closes https://github.com/openshift-metalkube/dev-scripts/issues/211
=> Limit api workers to 12

runmariadb.sh
Fixing location for the default mariadb conf file and adding variable to set it up.
Fixes #37
=> Fix mariadb conf file location

runmariadb.sh
Mariadb is failing to start:
```
2019-04-18 13:20:52 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2019-04-18 13:20:52 0 [ERROR] /usr/libexec/mysqld: unknown variable 'max_connects=64'
2019-04-18 13:20:52 0 [ERROR] Aborting
```
=> Fix incorrect mariadb configuration

runironic.sh
Enable ironic to clean disk metadata only.
=> Enable ironic cleaning

rundnsmasq.sh, runhttpd.sh, runironic.sh, runmariadb.sh
Store the logs from the Ironic containers in shared area to facilitate log rollup.
This also enables storing of the ironic python agent deploy logs from each node's
deployment.
=> Store Ironic container logs in shared mount

rundnsmasq.sh
This is consistent with how iptables rules are added in other containers and
will allow these sets to be removed from external scripts.
=> Add iptables rules in dnsmasq

Dockerfile
Moving to use a repository that has passed the RDO
ci should protect us a bit better from regressions.
=> Switch from "current" to "current-tripleo-rdo"

runironic.sh
Our dnsmasq config is setup to send "ipxe.efi" incases
where the host is UEFI booting. But by default ironic
sends a grub2 config when using UEFI boot. Switch
Ironic to use ipxe so they both match up and booting
UEFI works.
=> Set uefi_pxe_config_template to use the ipxe template

Dockerfile
This reverts commit 32d19dcf797429eba0c3394d74b8a4e952ae0b48.
This fixup is no longer needed so move back to using master
as the pin may stop working at some stage.
=> Revert "Pin tripleo-repos to avoid bug"

Dockerfile, installexporter.sh, runexporterapp.sh, runironic.sh
- Install the oslo messaging notifier Driver
- Configures ironic to use the new Driver
- Run a Flask Application under uWSGI to expose the metrics to Prometheus (by default it will run on port 5001 and this port need to be accessible for the Prometheus Container)
=> Support ironic_prometheus_exporter

inspector.ipxe, runironic.sh
Requires https://github.com/metal3-io/ironic-inspector-image/pull/21 and a recent IPA image.
=> Publish ironic endpoint via mDNS

Dockerfile, runironic.sh
Apparently, iptables are not installed by default. This is hidden
by the fact that the script doesn't fail on errors. And it hides
the fact the the mdns iptables commands are not correct.
=> Install iptables explicitly and correct the iptables lines

runironic.sh
=> Do not use hard coded Python 2

Dockerfile
There may be security vulnarabilities in the pre-installed packages,
let's make sure we always have the latest versions.
=> Update all packages when building an image

inspector.ipxe
After https://github.com/metal3-io/ironic-inspector-image/pull/25
these parameters are distributed via mDNS. Duplicating them here is
confusing, since this image is supposed to be for ironic.
=> Stop defining inspection kernel params in ironic-image

Dockerfile, configure-ironic.sh, runironic-api.sh, runironic-conductor.sh, runironic-exporter.sh, runironic.sh
We want to stop running several processes in one container, since it
violates container good practices and makes collecting logs and
health checking much harder.
=> Allow running ironic API, conductor and exporter separately

Dockerfile, installexporter.sh, runexporterapp.sh
This commit changes the ironic-image to use the
ironic-prometheus-exporter Package that is now available
in RDO.
- Updated Dockerfile
- Removed installexporter.sh
- Updated runexporterapp.sh
=> Start using ironic-prometheus-exporter package

runironic-api.sh
Ironic API will happily start without database connection, while
Conductor requires database on start-up. Running dbsync in two
places is potentially racy, so limit it to Conductor only.
=> Limit dbsync to only the Conductor entry point

Dockerfile, configure-ironic.sh, ironic.conf
This is consistent with ironic-inspector and results in a more complete
image. The options are sorted for readability.
=> Do static configuration of ironic.conf when building the image

runexporterapp.sh
Prometheus has a default port for the ironic-prometheus-exporter[1]
[1] https://github.com/prometheus/prometheus/wiki/Default-port-allocations
=> Change ironic-prometheus-exporter port

configure-ironic.sh
This still causes mdns queries responded on the interface the bridge is attached to.
I'm not sure if it's a problem or an implementation detail.
=> Limit mDNS to the provisioning interface

Dockerfile, runexporterapp.sh
Switching to gunicorn, since uwsgi is not available in the OSP packages.
=> Switch to gunicorn

ironic.conf
Default is 600 seconds, to get it below 5 minutes and not to hit
some BMCs on the sixty second interval, make the interval
slightly more than two and a half minutes
=> Increase the sensor data collection interval

Dockerfile, configure-ironic.sh, inspector.ipxe, ironic.conf, runexporterapp.sh, runironic-exporter.sh, runironic.sh
This patch contains changes needed to be able to use Ironic Stein.
It has dependencies from other patches in other related repos
and they should all be merged at the same time, following the order below,
to guarantee a correct behavior.
Full patch set:
https://github.com/openshift-metal3/dev-scripts/pull/680
https://github.com/metal3-io/ironic-image/pull/79
https://github.com/metal3-io/ironic-inspector-image/pull/30
https://github.com/metal3-io/ironic-ipa-downloader/pull/3
=> Changes to use Ironic Stein

rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runmariadb.sh
I noticed that it's possible for the dbsync in the conductor script
to fail (if mariadb is not yet up), which is silently ignored and
results in a broken Ironic.
It's probably one of many possible failures, so lets set -e so containers
exit when an error happens, which allows for automated restart e.g
via k8s or systemd.
=> Add set -e to all the entrypoint scripts

rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runmariadb.sh
(updated to revert)
We have always been ignoring errors from the iptables
commands(on master nodes). Revert this while we figure
out a way to eliminate them altogether.
This reverts commit 7e7eb9a.
=> Revert "Add set -e to all the entrypoint scripts"

dnsmasq.conf
Having DNS enabled causes issues when using this image on the bootstrap
node in openshift. If the dnsmasq container starts before coredns,
coredns refuses to start as dnsmasq has taken port 53.
=> Disable listening for DNS

configure-ironic.sh, rundnsmasq.sh, runhttpd.sh
We've seen some issues where the static-ip-refresh doesn't happen quickly
enough, and/or static-ip-set from initContainers expires before we start
the ironic containers.
To ensure we don't fail in that case, wait for the provisioning IP to be
assigned, then the exact order of container start is not important, and
we'll wait until static-ip-refresh has configured the nic.
=> Wait for PROVISIONING_INTERFACE to be up

runironic-conductor.sh
I've seen some situations where mariadb is not up soon enough for the
dbsync, despite the 10 retries done inside ironic-dbsync.
In this situation we start the ironic services anyway and since #80 got reverted,
we can't rely on pod/container restart to handle this, so lets retry inside
the script logging a warning instead.
=> Retry dbsync until success

Dockerfile
This is a dependency of the ironic packages (via the python2-oslo-db
package) already, and copying this dependency to the downstream el8
based dockerfile has caused issues since[1] made some of the image
building checks stricter, I assume this is because the package name
is different but I don't have a specfile reference atm.
This has led to [2] failing CI, and rather than just fix that downstream
we should probably make things consistent and remove this spuruious
install, then let RPM dependencies defined by the package maintainers
do the right thing on each platform?
[1] https://github.com/openshift/images/pull/11
[2] https://github.com/openshift/ironic-image/pull/15
=> Remove explicit install of python-PyMySQL

Dockerfile
There's no need to keep it around, and we tend to do this in other
images ([see OpenShift's baremetal installer Dockerfile](https://github.com/openshift/installer/blob/fac6d0ae60d15568faf118e5c0463ddec621a530/images/baremetal/Dockerfile.ci#L17)). The reduction is probably less than 100kB, but every byte counts.
=> Remove yum cache from image file

Dockerfile, configure-ironic.sh, inspector.ipxe, ironic.conf, runironic-exporter.sh
This patch adds back the features that were removed because we
were on Stain branch:
- continuous introspection
- ironic-prometheus-exporter
- mdns support
Also fixes #102 
Please merge this and https://github.com/metal3-io/ironic-inspector-image/pull/38 at the same time!
=> Re-adding Train features

inspector.ipxe, ironic.conf
The mdns feature is not compatible with ipv6 yet.
=> Disabling mdns for ipv6 testing

configure-ironic.sh
Removing a forgotten mdns configuration parameter that
might interfere if mdns is disabled.
=> Removing forgotten mdns conf param

ironic.conf
Currently, Ironic container does not enable RAID interfaces. This PR aims to add supported RAID interfaces into `ironic.conf` in order to support RAID configuration in Ironic provisioner.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
Co-Authored-By: Dao Cong Tien <tiendc@vn.fujitsu.com>
=> Enable RAID interfaces for Ironic container

Dockerfile
That's a generic python package and should be kept that way.
=> Use generic python-chardet

Dockerfile
The python-chardet package is a dependency of python-requests so no
need to install it explicitly.
=> Do not install python-chardet explicitly

configure-ironic.sh
With 4.3, we can re-enable fast_track provisioning again. In my testing it seems to work correctly, our inspector configuration already leaves the nodes powered on.
https://github.com/openshift-metal3/dev-scripts/pull/824 needs to land first
=> Enable fast_track provisioning for nodes

Dockerfile, configure-ironic.sh, dnsmasq.conf.ipv4, dnsmasq.conf.ipv6, ironic-common.sh, rundnsmasq.sh, runhealthcheck.sh, runhttpd.sh
This commit adds support for IPv6. When $PROVISIONING_IP is specified,
which may be an IPv6 address, the various containers will wait for that
IP to become available on an interface.
If the IP is IPv6, then we use an IPv6-specific configurations. Note,
IPv6 hosts are expected to be using UEFI boot, as we use snponly.efi.
snponly.efi uses the UEFI network stack instead of the iPXE drivers.
When using EDK2 OVMF + iPXE + ipxe.efi, we have seen lock-ups in
initialization of the hardware devices.
As neither CentOS nor RHEL distribute iPXE builds with IPv6 support, we
build them from source as part of the container build.
=> Changes needed for IPv6

Dockerfile, rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runironic.sh
We don't appear to need these, infact they output
errors on container startup...
=> Remove iptables filters from ironic containers

rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runironic.sh, runmariadb.sh
Rely instead on the logs to std out/err for each container
Fixes: #46
=> Stop logging to file

rundnsmasq.sh
the variable was not being replaced by sed
=> Replace IRONIC_IP in dnsmasq config

Dockerfile, ironic.conf
In order to boot instances via virtual media in UEFI,
we need to be able to master an EFI image which contains
the bootloader and related files.
In this case, we're collecting the shim and grubx64.efi
into the image which will be used by the EFI firmware to
load the bootloader.
=> Adds initial redfish UEFI virtual media boot

README.md
Currently, log files is disabled by #46. This PR aims to remove this outdated infomation from README.md
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove outdated instruction related to log files

runhttpd.sh, runironic-conductor.sh
The bootloader was copied to the html folder in runironic-conductor
while some other scripts are used to start ironic. Moving the copy
to runhttpd as the file is served by httpd.
=> Fix bootloader copy

configure-ironic.sh
It was missing the port, always going to port 80 when httpd
listens on 6180 in BMO deployments
=> add HTTP port in bootloader configuration for ironic

Dockerfile
Start testing images with Centos 8 as base.
=> Start using Centos 8 as base

rundnsmasq.sh
After the move to centos8, python3 is the only python installation.
changing the python version to 3 in the dnsmasq script.
=> Fix python version in rundnsmasq

Dockerfile
The removal of linuxefi should not be significative as the file
doesn't exist in Grub2 upstream but it's just distro specific.
It was removed from the grub2-efi-x64-modules package for that
reason.
=> Use Centos 8 as base for the builder

README.md
Adding the master build status for Ubuntu and Centos, V1alpha1 and v1alpha2
=> Add E2E build status in Readme

rundnsmasq.sh
Its required when rendering /etc/dnsmasq.conf.j2
=> export HTTP_PORT

ironic.conf
When operating in an environment with networking issues, these two
seem to be the biggest sources of deployment/cleaning failures:
1) Substantially increase the number of retries for the ramdisk commands.
2) Enable PXE boot retries after 20 minutes of not hearing from the ramdisk.
See https://bugzilla.redhat.com/show_bug.cgi?id=1822763
=> Increase command retries and add PXE booting retries

dnsmasq.conf.j2
As part of the UEFI stack, a network stack is available. The iPXE
binary that implements this stack, and only this stack support is
snponly.efi, where as ipxe.efi instead tries to load network driers
that have been authored and incorporated into the ipxe.efi binary
itself.
These drivers are redundant in UEFI mode, and we should not need
them. As such, we should realistically only be using snponly.efi.
If not used, we get an error about no networks having been found
upon loading ipxe.efi.
rhbz# 1830161
=> Use snponly.efi instead of ipxe.efi for IPv4

Dockerfile
The current-tripleo repo is now available for centos8 and we
should use it.
=> Use tested packages

ironic-common.sh
This PR fixes an issue when using routable IPv6 addresses for the provisioning network. The previous grep command only matched local unicast addresses, this new grep will match any IPv6 address, but the link local scope.
The httpd container keeps waiting for "PROV_IFACE" to be configured otherwise.
=> Allow any IPv6 address to be configured for provisioning, but link local scope

ironic-common.sh
The prefix was captured with the IP address. This change strips it
Fixes #155
=> Fix the IP address parsing in ironic-common.sh

configure-ironic.sh, inspector.ipxe, ironic.conf
Without it ironic will never learn that the ramdisk has been booted
for inspection, requiring a reboot despite fast-track enabled.
=> Update inspection configuration to enable fast-track

configure-ironic.sh, inspector.ipxe, ironic.conf
Without this configuration, the ipmitool timeout is 1 second. This is too short
for vbmc. This commit uses the ipmitool retry feature and extends the
timeout.
This PR also set console=ttyS0 in the IPA kernel parameter to gather IPA logs
in Metal3-dev-env
=> Configure ironic to use Ipmitool retries

README.md, configure-ironic.sh
As more use cases are using this image and may need to tweak
various config options. Add the method to set arbitary options
rather then having to add a new option for each case.
Potential solution (the ironic part) to https://github.com/metal3-io/ironic-image/issues/143
Another alternative method might be to mount a partial ironic.conf to be merged into /etc/ironic/ironic.conf , I've leaned in the direction of the env variable as its more consistent
with that we currently have
Marking as WIP until we discuss whats best.
=> Add ability to set arbitrary ironic configs

configure-ironic.sh
This commit adds the support to run ironic using `http_basic`.
To enable that is necessary to set USE_HTTP_BASIC to true, and also
specify values for the following enviroment variables:
-IRONIC_HTTP_BASIC_USERNAME
-IRONIC_HTTP_BASIC_PASSWORD
=> Add http_basic auth support

ironic.conf
The default MD5 is not compatible with FIPS mode. See
https://bugzilla.redhat.com/show_bug.cgi?id=1853302
=> Set the hash ring algorithm to SHA256

configure-ironic.sh, ironic.conf, runironic-conductor.sh, runironic.sh
By default, ironic-conductor currently binds to any IP address, so it is
accessible outside of the pod. When no authentication method is used for
json-rpc, bind only to localhost so that only other containers in the
same pod can connect to the json-rpc server.
This will break any deployments that put ironic-conductor and ironic-api
in separate pods but do not specify basic_auth. This is probably a good
thing.
=> Limit unauthenticated json-rpc to localhost interface

configure-ironic.sh, ironic.conf, runironic-api.sh, runironic-conductor.sh, runironic.sh
Make HTTP basic auth configuration simpler, more flexible, and a better fit and more secure when used with standard k8s deployment techniques.
* Add the missing basic auth configuration options for ironic-inspector
* Allow basic_auth to be configured independently on different interfaces, based on the presence of the required configuration data, rather than using a single global USE_HTTP_BASIC environment variable.
* Expect all server credentials to be passed in the form of an HTTP_BASIC_HTPASSWD environment variable containing both the username and the *hash* of the password, in the htpasswd format. This is more secure, as it allows containers not to hold a copy of the password when they don't need it purely for authenticating connections.
* Keep server auth user files locally rather …
=> Simplify HTTP basic auth configuration

README.md
**What this PR does / why we need it:**
This commit adds some parameters for the ironic configuration
=> Make ironic timeouts customizable

configure-ironic.sh, runironic-api.sh, runironic-conductor.sh, runironic.sh
The ironic-conductor process needs to authenticate to the
ironic-inspector API, so we need to pass the auth config file options to
it also.
=> Configure ironic-conductor to auth to ironic-inspector

Dockerfile, httpd-modules.conf, httpd.conf
Leave httpd with the minimum needed for metal3,
in particular we wanted to disable directory listing and
http TRACE. But disabling everything we don't use seems
prudent.
=> Remove all unused modules

ironic.conf
I'm working on BIOS configuration with the `idrac-wsman` driver. Since this requires enabling the interface, I've edited the `ironic.conf` to do so.
=> enable idrac-wsman BIOS interface

ironic.conf
A temporary fix for the issue #188 
We can enable idrac once we have done proper investigation.
=> Disable bios interfaces idrac-wsman

configure-ironic.sh
Make the name consistent with inspector.ipxe.
=> Use collector name in ironic.conf expected by IPA

Dockerfile
In the private environment of some users, it is forbbiden during redirectin.
the commonly used github URL looks better.
=> Change ipxe git in dockerfile

runironic.sh
Using the default entrypoint, which runs both the ironic-api and
ironic-conductor processes in the same container, the container should
exit immediately if either of those processes ends.
=> Exit if ironic-api or ironic-conductor exits

Dockerfile, ironic.conf
ironic needs syslinux-nonlinux to generate a
bootable ISO image for virtmedia install on bios.
=> Install configure for syslinux-nonlinux

dnsmasq.conf.j2
To prevent collisions on address allocation for MAC addresses
that are too close to each other when starting nodes in batch
Fixes: #195
=> add dhcp-sequential-ip to dnsmasq config

configure-ironic.sh, inspector.ipxe, ironic.conf.j2, runhttpd.sh
This commit allows the user to start Ironic using TLS on all
endpoints, by setting the following environment variables:
- CACERT_FILE: path to the CA cert
- CERT_FILE: path to the cert
- KEY_FILE: path to the key
=> Add TLS support in Ironic configuration

configure-ironic.sh, ironic.conf.j2
Previously we disabled for some reason, but we had people using
the ironic prometheus exporter in Metal3.
Add a new env variable `SEND_SENSOR_DATA` that will be used to
define if it will be enabled or not.
=> Make sensor_data collection configurable

ironic.conf.j2
Work around https://storyboard.openstack.org/#!/story/2008288 by setting
the DEFAULT.host config option to the host portion of a URL, meaning
that IPv6 addresses are surrounded by [], rather than just the raw IP
address. This is how it is ultimately used inside Ironic.
This solution works both with and without the fix for the issue in
Ironic (https://review.opendev.org/759877).
Fixes #210
=> Use [] around IPv6 address for conductor host config

Dockerfile, ironic.conf.j2
Avoid rebuilding GRUB2 since it invalidates its signature. Ironic
is able to build correct ISO images if you provide it with
a distribution specific EFI config path.
See https://review.opendev.org/760434
=> Secure boot compatible ESP image

Dockerfile
When possible, we should merge RUN commands to reduce the number
of layers in the image.
=> Merge RUN commands to reduce layers number

Dockerfile
Apparently, I cannot correctly follow my own documentation :(
=> Correct the destination grub path when building an ESP image

configure-ironic.sh
12 is a lot of workers. With up to 100MiB of RAM per each, ironic-api
processes may occupy more than 1GiB of RAM in such configuration.
Since even CERN uses 2 workers in their configuration, we should
be fine with no more than 4. A similar change is made upstream:
https://review.opendev.org/761185
=> Limit the default number of API workers to 4

ironic.conf.j2
Add Redfish as a BIOS interface to allow retrieving BIOS configuration
using Redfish.
=> Add redfish as an enabled BIOS interface

Dockerfile, README.md, runlogwatch.sh
This is the first step in series of PRs implementing this design proposal: https://github.com/metal3-io/metal3-docs/blob/master/design/ironic-debuggability-improvement.md
=> Add new entry point script to dump ramdisk host provisioning logs

configure-ironic.sh, ironic.conf.j2
We excluded these options from the initial proposal because they
reduce security. But since the provisioning IP may not be easily
predicted, it may be hard to generate suitable certificates, so
the insecure option is added to fascilitate two-step migration
from fully insecure HTTP to fully secure HTTPS.
=> Add options to disable TLS validations

Dockerfile, prepare-image.sh
Convert the current PKGS_LIST to ENV as we should not really touch it.
Introduce the EXTRA_PKGS_LIST ARG to allow specifying a file
containing a list of extra packages to install.
The goal is to allow installing packages from different sources
to test them.
=> Introduce separate ARG for extra packages list

ironic.conf.j2
This adds three closely related features:
* The noop management interface allows skip management actions
(boot device and mode) for a node. The PXE netboot fallback
is enabled for it to be able to local boot properly.
* The manual-management hardware type also skips power actions.
This change misses the agent power interface that can allow
the manual-management hardware type to use a running agent
for power actions to achieve a limited deploy capability
without BMC credentials [1]. We need to enable it conditional
on fast-track (and it's disabled in the metal3 CI).
[1] https://docs.openstack.org/ironic/latest/admin/agent-power.html
=> Add support for noop management and manual-management

Dockerfile, README.md, patch-image.sh, prepare-image.sh
This change allows users to apply patches to the images during build
time directly from gerrit using the new arg PATCH.
At the moment, it's limited to a single project per image; future
patches will allow applying patches from multiple projects, and
also from local directories.
=> Provide a way to apply upstream patches to the image

runironic-api.sh
Currently the API will start even if the conductor is still
starting up, which can lead to failures if you try to deploy
nodes as soon as the API is accessible.
Co-Author: Steven Hardy <shardy@redhat.com>
This is a rework of a old PR to deal with this https://github.com/metal3-io/ironic-image/pull/122
but instead of looking at the drivers in the conductors table we look at hardware_types in conductor_hardware_interfaces
A change in the way ironic registers drivers is proposed here (this would also deal with the issue)
https://review.opendev.org/c/openstack/ironic/+/764911
=> Wait for expected number of drivers starting API

ironic-common.sh
Using grep with a user-supplied query that is likely to contain `.`
characters is not the most robust method of searching for a string in
some output. For example, passing `PROVISIONING_IP=192.168.1.2` would also
match e.g. 192.168.122.1. Avoid this by searching for a fixed string,
including the characters before and after the IP address.
The best way to do this would be using the json output from the ip
command:
```
[ -n $(ip -j addr show | jq -r ".[] | .addr_info[] | .local | select(. == ${IRONIC_IP})") ]
```
and something similar to get the IP address when only the provisioning
interface is specfied:
```
ip -j add show scope global up dev ${PROVISIONING_INTERFACE} | jq -r .[0].addr_info[0].local
```
but continuing to do it with grep avoids having to install the `jq` tool.
This also …
=> Make searching for Provisioning IP robust

Dockerfile
Supplying a blank arg to COPY results in all of
the files in the source directory being copied into
the image into /tmp for docker/podman build (or "/"
if using imagebuilder). Give it a default of a file
that exists to avoid this happening.
=> Supply a default for COPY args

config/ironic.conf.j2, ironic-packages-list.txt
This change adds configuration for the iLO driver as per https://docs.openstack.org/ironic/latest/admin/drivers/ilo.html. Also see #243.
The hardware interfaces for ilo are added to ironic.conf.j2. The python3-proliantutils dependency has also been added.
I'm currently testing this image with iLO 4.
=> Support iLO4 and iLO5 BMCs

config/inspector.ipxe.j2, config/ironic.conf.j2, scripts/configure-ironic.sh
Add the inspector kernel param to include vlan interfaces and
associated IP addresses in the introspection report. This feature
was added to IPA in
https://review.opendev.org/c/openstack/ironic-python-agent/+/760570.
By default all VLAN interfaces are included in the report using LLDP
info from the switch to determine the VLANs. An override is provided
to define a particular VLAN interface if LLDP is not enabled.
=> Include vlan interfaces in introspection report

ironic-scripts/runironic-api, prepare-image.sh
Now that https://github.com/metal3-io/baremetal-operator/pull/728 has
merged, we can remove net-tools installation command.
=> Remove net-tools installation

Dockerfile
an alternative would be to set it to one of the valid binaries, like /bin/runironic-api
=> Remove the docker entrypoint as it does not exist

Dockerfile
This is to avoid failures when building the image due to "Disk full"
=> Increase ESP size

scripts/runironic-inspector
Solve the following issues:
/bin/runironic-inspector: line 32: [: missing `]'
/bin/runironic-inspector: line 44: [: missing `]'
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
=> Add space before ']'

prepare-image.sh, scripts/configure-ironic.sh, scripts/runhttpd, scripts/runironic-api, scripts/runironic-conductor, scripts/runmariadb
When the TLS certificate is updated, Ironic will reload (or restart) to get the new certificate.
=> Restart Ironic when certificate is updated

ironic-config/ironic.conf.j2
The new ramdisk_image_download_source allows to set where the boot iso
image will be served from.
Related to the ironic change https://review.opendev.org/c/openstack/ironic/+/788734
=> Add parameter to set boot iso source

scripts/runmariadb
Issue: For some reason the script mysqld_safe_helper is used to run mysqld. This script runs with `--user=mysql` and `--log-error=/var/log/mariadb/mariadb.log`. This causes the `permisison denied` error because user mysql tries to  write to `/var/log/mariadb/mariadb.log` which, in this repo, is a symlink of root's stdout. 
Error message:
`/usr/bin/mysqld_safe_helper: Can't create/write to file '/var/log/mariadb/mariadb.log' (Errcode: 13 "Permission denied")`
This PR solves the problem by removing the symlink hack and make the error log go to stdout in a proper way.
=> Fix the "permisison denied" bug properly

ironic-config/ironic.conf.j2
Set the ironic conf setting `webserver_verify_ca` to False
if IRONIC_INSECURE is True (to disable TLS validation) or set
it to path to CA_BUNDLE file if new IRONIC_CA_PATH env
variable is set.
By default it will be set to True.
=> Set webserver_verify_ca to bool or certificate path

resources/sushy-tools/Dockerfile, resources/vbmc/Dockerfile
Move sushy-tools & vbmc Dockerfiles to ironic-image repo in order to avoid building their images on every single pull request in metal3-dev-env. This will reduce the time it takes for integration test to run in metal3-dev-env and for master jobs that run every day.
Discussion thread on [slack](https://kubernetes.slack.com/archives/CHD49TLE7/p1621868516039800).
After this PR is merged, I will update quay to point ironic-image repo.
=> Add sushy-tools & vbmc Dockerfiles

prepare-image.sh, scripts/runhttpd, scripts/runironic-api
Currently, when deploying ironic and ironic-inspector, there are two httpd instances. One is deployed in the script `runironic-api`, and this instance is used to serve file for IPA and to run as a WSGI web server for ironic-api. The other one is deployed in the script `runhttpd`, and it is used to also serve file for IPA and to run as a reverse proxy for ironic-inspector. This causes the problem when two httpd instances open the same port to serve file for IPA. This PR removes one instance to fix the issue. Also, this removal will simplify the configuration and boost the overall performance.
=> Keep only one httpd instance for the Ironic deployment

ironic-config/ironic.conf.j2, scripts/configure-ironic.sh
In order to allow provisioning of external nodes, we need to be able to
call back to Ironic on an external IP address.
=> Add options for external_http_url and external_callback_url

ironic-config/ironic.conf.j2
When bios_interface  set to irmc, the master will continue to restart during the IPI
configuration process, see https://github.com/openshift/installer/issues/4963
so temporarily remove irmc from enabled_bios_interfaces.
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
=> remove irmc from enabled_bios_interfaces

ironic-config/ironic.conf.j2
This commit adds the new ironic configuration option
``[ipmi]/cipher_suite_versions``.
Allowing ipmi to try different values in case of the
default cipher suite is not supported.
=> Add cipher_suite_versions config

ironic-config/ironic.conf.j2
This option should contain only parameters unique to inspection.
Standard kernel parameters go to boot interface configurations
(pxe_append_params, kernel_append_params).
Add missing [ilo] configuration since ilo-virtual-media is supported.
=> Clean up [inspector]extra_kernel_params

README.md, scripts/ironic-common.sh
The point of this PR is to allow users to:
1. not have to provide the PROVISIONING_INTERFACE (as it has to be the same for all hosts)
2. instead make use of the know mac addresses that we have in the bmh.Spec.BootMACAddress to calculate the interface
An example of how to do this is here (openshift specific): https://github.com/openshift/cluster-baremetal-operator/pull/149
=> Add support for deriving the PROVISIONING_INTERFACE from a mac address

prepare-image.sh, scripts/runhttpd, scripts/runironic-inspector
When using httpd as the reverse proxy for ironic inspector, the httpd server will listen at 5050, and forward the traffic to port 5049. For that reason, we need to set the ironic inspector endpoint to this port. Otherwise, the traffic between ironic inspector and other components are not encrypted.
Also, this PR solves a problem with non-proxy case. Currently, if TLS is enabled, but we don't use the reverse proxy, it can cause problem. This PR solves that.
=> Update the inspector endpoint to port 5049 when using the reverse proxy

scripts/runironic-api
The root cause has been fixed in Ironic.
This reverts commit 3c8acf4f3b26a5055362b091aec2dfeb8b06d89d.
=> Revert "Wait for expected number of drivers starting API"

prepare-image.sh
This change adds a flag that disables installing documentation from
RPMs. Additionally, prevent installing weak dependencies globally.
=> Prevent installing docs via a DNF flag

ironic-config/ironic.conf.j2
Tokens are mandatory in Ironic and enabled by default for a while.
=> [Trivial] Remove no-op require_agent_token

ironic-config/ironic.conf.j2
We only enable vendor interfaces for a subset of hardware types, there
is not reason for that. The Redfish vendor interface, for example,
contains a call to eject virtual CD, which we may use in the future.
=> Enable missing vendor interfaces

resources/sushy-tools/Dockerfile
Bump sushy-tools version to 0.17.0 to pick up BIOS attribute registry support for testing.
=> Bump sushy-tools version

prepare-image.sh, resources/vbmc/Dockerfile
The upstream openstack tripleo team decided to move the `tripleo_repos` folder under `plugins/module_utils/` https://github.com/openstack/tripleo-repos/commit/77dc5794ac880abc57927af08e70e99d2a972f84
Due to this, when building the ironic container, we end us with a `404 Not Found` error.
Updating the script as per as the new upstream repo structure.
=> Update tripleo_repos location

ironic-config/ironic.conf.j2
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
We are currently modifying [python-scciclient](https://opendev.org/x/python-scciclient/src/branch/master/scciclient/irmc/elcm.py#L701-L739) to avoid the master restart due to obtaining BIOS settings during IPI installation.
After the modification is complete, we can re-enable irmc BIOS interface.
=> Enable irmc bios interface

ironic-config/ironic.conf.j2, scripts/configure-ironic.sh
In order for IPA to call back into ironic inspector when being
used on external networks, we'll need to set this as well.
=> Add inspector callback_endpoint_override

resources/vbmc/Dockerfile
Introduce an ARG BASE_IMAGE that allows customizing the base image used
to build the container.
This can be useful for quickly changing base image for testing,
especially in automated setups.
=> Allow customize base image

scripts/configure-ironic.sh
During virtualmedia deploy the port in the iso url is missing causing
the deploy to fail.
For more info please see https://bugzilla.redhat.com/show_bug.cgi?id=1990316
=> Fix missing http port in iso url

Dockerfile, prepare-image.sh, resources/vbmc/Dockerfile
Images taken from https://www.centos.org/centos-stream/
=> Switch to Centos 8 Stream base image

main-packages-list.txt
`procps` is missing in centos 8 stream. However, we need it to use `ps` at some places, like this: https://github.com/metal3-io/ironic-image/blob/abc12be6df2a01e489e70b54aa7e291710fe1ef5/scripts/runhttpd#L91
This PS adds `procps` to the image, so `ps` is available.
=> Add procps package to make `ps` available

Dockerfile
Introduce an ARG BASE_IMAGE that allows customizing the base image used
to build the container.
This can be useful for quickly changing base image for testing,
especially in automated setups.
=>  Allow customize base image

ironic-config/apache2-ironic-api.conf.j2
Just `/v1/heartbeat` is also valid.
=> Remove the trailing slash from the heartbeat rule

resources/sushy-tools/Dockerfile
This commit bumps the version of sushy-tools to 0.18.0, this is the
latest release that includes new features.
=> Bump sushy-tools to 0.18.0

main-packages-list.txt
Minimum versions are outdated and not needed anymore.
=> Remove outdated versions

Dockerfile
Builder does not use any local content. Copying it causes constant
rebuilds of iPXE when building locally.
=> Dockerfile: stop copying . to builder

Dockerfile, ironic-config/ironic-python-agent.ign.j2, scripts/configure-coreos-ipa, scripts/coreos-ipa-common.sh, scripts/runhttpd
This adds a script we initially created [downstream](https://github.com/openshift/ironic-image/blob/master/scripts/configure-coreos-ipa) 
This is useful for testing metal3 with coreos based builds and the [ironic-agent-image](https://github.com/metal3-io/ironic-agent-image/) via the [customizable deploy procedure](https://github.com/metal3-io/metal3-docs/blob/master/design/deploy-steps.md) that [landed in BMO](https://github.com/metal3-io/baremetal-operator/pull/884).
Adding this means we can close a docs gap and show how to deploy e.g [Fedora CoreOS](https://getfedora.org/en/coreos?stream=stable) via metal3 and also enable easier developer testing of this flow.
This script can be deployed alongside Ironic in the same pod (which is how we use this script downstream as an initContainer), …
=> Add configure-coreos-ipa script

Dockerfile
iPXE started using release tags, let's start using them instead of
pointing to a commit hash.
Release 1.21.1 includes commit [1] that enables IPV6 by default,  removing
the need for the hack before building ipxe.
[1] ipxe/ipxe@0c25daa
=> Update ipxe source to support IPV6 by default

Dockerfile, README.md, ironic-rpm-list.txt, ironic-source-list.txt, main-packages-list.txt, prepare-image.sh, scripts/configure-ironic.sh
This patch adds a build-time argument that allows to build the ironic container image using source code instead of RPMs
At the moment this option should only be used for testing purpose, to simplify building images using the latest code or local patches
It is possible to test it using metal3-dev-env with the patch https://github.com/metal3-io/metal3-dev-env/pull/839
=> Add option to build image using source code directly

ironic-rpm-list.txt, ironic-source-list.txt, prepare-image.sh
=> Follow-up to build image from source

scripts/coreos-ipa-common.sh
When we get images from the image builder, they will contain the
Ignition file. Only pass an Ignition URL on the kernel command line if
the configure-coreos-ipa script has been run to create an ignition file
locally. We will not run this script when using the image builder.
However, we always want to set the rootfs location in the kernel args,
even when we haven't run configure-coreos-ipa because we are using the
image builder instead.
=> Don't always pass ignition config in PXE kernel args

prepare-image.sh
For whatever reason, Python itself depends on it in CentOS.
=> Do not remove pip in the source build

ironic-config/ironic.conf.j2
This path is where the cache is maintained, and Ironic cleans it up
periodically. Keeping it in /shared/tftpboot means that Ironic may
remove files from it.
=> Move tftp_master_path to a subdirectory (fixes #333)

ironic-config/ironic.conf.j2
* ipxe_enabled no longer exists
* pxe_append_params -> kernel_append_params
* (uefi_)pxe_config_template not used for iPXE
=> Clean up deprecated and unnecessary PXE configuration

Dockerfile, ironic-config/apache2-ironic-api.conf.j2, ironic-config/ironic.conf.j2, ironic-inspector-config/ironic-inspector.conf.j2, prepare-image.sh, scripts/configure-ironic.sh, scripts/ironic-common.sh, scripts/runhttpd, scripts/runironic, scripts/runironic-api, scripts/runironic-conductor
This series of commits adds a new entrypoint `/bin/runironic` that uses the new combined `ironic` executable to start both API and conductor in one process. TLS is expected to be handled by a reverse proxy setup, similar to Inspector. The default for the new executable is to be backed by SQLite, not MariaDB for a smaller footprint.
=> Add a combined Ironic launcher

scripts/ironic-common.sh
This PR removes the -s parameter of `ipcalc`. 
- `-s ` makes `ipcalc` not printing error message when error occurs. Therefore, removing this parameter should not affect the workflow, but can also provide some clues when there is an error.
- Folks who are more familiar to Ubuntu or other OSes may feel confusing when reading code because in other OSes, `-s` mean splitting. Therefore, removing this parameter makes it easier to maintain the code.
=> Remove unnecessary flag of ipcalc

ironic-config/ironic.conf.j2
This new feature provides a history of all events for a node. We don't
use it, and it creates an additional load on the database. Disable.
=> Disable the node history feature

ironic-rpm-list.txt
We support running API+conductor combined, but we don't actually install the corresponding RPM.
=> Install the RPM of the combined Ironic

ironic-config/ironic.conf.j2
The fall-back to [pxe] is deprecated.
See also: https://github.com/openshift/installer/issues/5504
=> Set [irmc]kernel_append_params explicitly

ironic-config/apache2-ironic-api.conf.j2, ironic-inspector-config/inspector-apache.conf.j2, scripts/configure-ironic.sh, scripts/runhttpd, scripts/runironic-inspector
It's common to use different values, which gets confusing when both
services are proxied through the same HTTPd.
=> Add different variables for htpasswd of ironic and inspector

ironic-config/apache2-ironic-api.conf.j2
1) The authentication code assumes /v1 prefix, but Ironic has redirects,
e.g. /drivers -> /v1/drivers
2) The lookup/heartbeat endpoint rules are overridden by the generic
rule, so they don't have effect.
While here, fix some whitespace.
=> Fix authentication with Ironic reverse proxy

scripts/configure-ironic.sh, scripts/ironic-common.sh
When Ironic is in reverse proxy mode, it is also used by runhttpd.
=> Move LISTEN_ALL_INTERFACES to ironic-common

ironic-inspector-config/inspector-apache.conf.j2
1) It blocks /v1/introspection/ but allows /v1/introspection, which
lists introspection results per node.
2) It does not block /v1/rules used to create introspection rules.
=> Fix authentication for inspector in reverse proxy mode

Dockerfile
glibc-gconv-extra was included by default in the past and
we need it otherwise mkfs.msdos will fail with:
``Cannot initialize conversion from codepage 850 to ANSI_X3.4-1968: Invalid argument``
``Cannot initialize conversion from ANSI_X3.4-1968 to codepage 850: Invalid argument``
subsequently making mmd fail with:
``Error converting to codepage 850 Invalid argument``
``Cannot initialize '::'``
This is due to the conversion table missing codepage 850, included
in glibc-gconv-extra
Fix https://github.com/metal3-io/ironic-image/issues/353
=> Fix missing codepage 850 in conversion table

OWNERS
Iury is the Ironic PTL (project team lead) and has been consistently
reviewing ironic-image changes in his reviewer role.
Stephen has moved to another role.
=> Promote Iury to approvers, remove Stephen

ironic-config/ironic.conf.j2
There seems to be an issue where ipmitool does not retry with different
ciphers. This could be worked around by letting Ironic handle the retry
instead.
Discussion on slack: https://kubernetes.slack.com/archives/CHD49TLE7/p1645523770977829
Here is a description of the issue we are having:
We have a (very old) hardware where IPMI cipher suite 3 is supported, but not 17. Due to https://github.com/metal3-io/ironic-image/blob/307e765800a701da39d6d2febd1bdbf6d36cb700/ironic-config/ironic.conf.j2#L140, we let ipmitool handle the retry loop. but then ipmitool only uses cipher 17 (we don't have https://github.com/ipmitool/ipmitool/commit/7772254b62826b894ca629df8c597030a98f4f72 in our ipmitool release). Due to https://github.com/openstack/ironic/blob/53a38f18d47d3fef5e9a7a8f6ecf5ab99b2f8e0f/ironic …
=> Let Ironic handle retry instead of ipmitool

scripts/runironic-inspector
Also add verbosity and exit on error
=> Fix missing semi-colon in runironic-inspector script

main-packages-list.txt
After switching to CentOS Stream 9 base image, our main custom IPA image building [jobs](https://jenkins.nordix.org/view/Metal3/job/metal3_main_openstack_ipa_and_ironic_image_building/71/console) started failing with pip3 being not found while doing a patch in the image. 
```
[91m+ pip3 install --prefix /usr dist/ironic-20.0.1.dev38.tar.gz
/bin/patch-image.sh: line 20: pip3: command not found
[0mThe command '/bin/sh -c prepare-image.sh &&   rm -f /bin/prepare-image.sh' returned a non-zero code: 127
make: *** [Makefile:145: build_ipa] Error 127
```
This PR adds [python3-pip](https://centos.pkgs.org/9-stream/centos-appstream-x86_64/python3-pip-21.2.3-5.el9.noarch.rpm.html) to the main packages list ~and uses that in the patch image script instead of pip3~
=> 🐛 Add python3-pip package to packages list to use pip3 in patch image script

Dockerfile, scripts/rundnsmasq
https://github.com/metal3-io/ironic-image/pull/152 seems to have removed the last use of ipxe.efi in favour of snponly.efi.
/cc @elfosardo
=> Drop unused ipxe.efi

ironic-config/ironic.conf.j2
There have been cases on some hardware where the power state change takes longer than the current default (60 seconds) to be reported. This does not need to be configurable.
=> Increase power_state_change_timeout setting

prepare-image.sh
There are dependency issues related to setuptools and pip unless they are
updated before other python packages are installed.
=> fix ironic source install

resources/sushy-tools/Dockerfile
Werkzeug 2.2.0 broke behavior of sushy-tools until version 0.20.0
is out.
=> Pin Werkzeug to 2.1.2 until newer version of sushy-tools is out

resources/sushy-tools/Dockerfile
This brings back full compatibility with latest versions of Werkzeug
after changes in 2.2.0
=> Update sushy-tools to version 0.20.0

ironic-inspector-config/ironic-inspector.conf.j2
When running ironic without TLS inspector is running without reverse proxy and it always listening on all interfaces, since we have already introduced an option to listen on a single interface #371 this PR add the option in the case we run ironic without TLS
=> Add option to to listen on a single inspector interface

ironic-config/apache2-ironic-api.conf.j2, ironic-config/ironic.conf.j2, ironic-inspector-config/inspector-apache.conf.j2, ironic-inspector-config/ironic-inspector.conf.j2, scripts/ironic-common.sh, scripts/runironic-inspector
Since httpd, ironic and inspector share a volume, there is no point
in allocating private ports and making their communication go through
the network stack. Allow using unix sockets instead.
=> Support for unix sockets in reverse proxy mode

ironic-config/ironic.conf.j2
To provision Dell servers with redfish, we need to enable the idrac-redfish in the raid interfaces of the Ironic configuration.
Fixes: #384
=> Support idrac-redifsh driver in raid interfaces of ironic configuration

ironic-config/dnsmasq.conf.j2, scripts/rundnsmasq
May be very useful when early resolving of hostnames is required.
=> Allow dnsmasq to work as a DNS forwarder

ironic-config/apache2-ironic-api.conf.j2, ironic-config/apache2-vmedia.conf.j2, ironic-inspector-config/inspector-apache.conf.j2
ServerName does not support IPv6 addresses, the verification fails when the second segment doesn't begin in a digit(it doesn't look enough like a port number).
We only have a single VirtualHost per "Listen" so it is the default. Remove the use of ServerName as we're not using it to differentiate between VirtualHosts.
=> Removed ServerName from VirtualHost Directives

scripts/configure-httpd-ipa.sh, scripts/runhttpd
```
cat /shared/html/inspector.ipxe  |grep callback
```
```
cat /shared/html/inspector.ipxe  |grep ipa
kernel --timeout 60000 http://x:6180/images/ironic-python-agent.kernel ipa-insecure=1 ipa-inspection-collectors=default,extra-hardware,logs systemd.journald.forward_to_console=yes BOOTIF=${mac} ipa-debug=1 ipa-enable-vlan-interfaces= ipa-inspection-dhcp-all-interfaces=1 ipa-collect-lldp=1  initrd=ironic-python-agent.initramfs console=ttyS0 ipa-ntp-server=x || goto retry_boot
```
ipa-inspection-callback-url value is empty.
=> Change variable to environment

README.md, ironic-config/dnsmasq.conf.j2, scripts/rundnsmasq
Depending on your environment, you should be able to use either GW or DNS.
=> Add DNS or GW for use by dnsmasq

README.md, ironic-config/dnsmasq.conf.j2
Add variables for dhcp-host and dhcp-ignore. These allow us to specify known hosts by listing the known MACs and then telling dnsmasq to ignore any host that is not known. This is useful if running multiple instances in the same network.
=> Add more DHCP options

prepare-image.sh
The sushy library is present in upper-consraints blocking the installation of any newer version (like dev versions). When installing sushy from source we need to remove it from the upper-constraints file.
=> Fix source build if building sushy from source

scripts/ironic-common.sh
httpd-infra is not running correctly on centos because of `PROVISIONING_MACS unbound value` after inroducing bash `set -u` in https://github.com/metal3-io/ironic-image/pull/370
=> 🐛  Fix centos httpd

resources/sushy-tools/Dockerfile
Apt gives out warnings that it doesn't have stable CLI for script usage. Replace apt with apt-get in Dockerfiles.
Also, it is a best practise to define DEBIAN_FRONTEND=noninteractive so the build will not ask you questions, but accepts the defaults, in case it needs any confirmation from user. Setting this avoids stalling builds in case there is a conflict, or configuration option added to the installed packages.
=> Dockerfiles: use apt-get instead of apt

prepare-image.sh
It forces using /var/log/ironic/ironic.log, which is not necessary in
containers and also grows indefinitely since log rotation is not enabled.
=> Remove RDO distribution configuration (finally fixes #46)

ironic-config/ironic.conf.j2
Configuring iLO Ironic driver to use web server for hosting images. This resolves an issue where it defaults to swift while running in standalone mode, breaking virtual media provisioning.
=> Configure Ironic iLO driver to use web server

main-packages-list.txt
Dosfstools and util-linux provide mkfs and mkfs.vfat binaries which are required for image creation operations performed by iLO driver.
=> Adding dosfstools and util-linux tools to ironic-image

resources/sushy-tools/Dockerfile
Sushy tools port is hard-coded in the Dockerfile this PR removes it since the default port is 8000 and allows parameterize the port from the config file e.g `SUSHY_EMULATOR_LISTEN_PORT = 8000`
=> Use sushytools port from the config file

README.md
Especially the `OS_<section>_\_<name>=<value>` looked broken when viewed on Github.
=> docs(readme): fix environment variable formatting

resources/sushy-tools/Dockerfile
This is the last instance of registry.hub.docker.com to align in main branches of actively developed Metal3 repositories.
=> set docker registry url to docker.io

Dockerfile, configure-nonroot.sh, prepare-image.sh, scripts/rundnsmasq, scripts/runhttpd, scripts/runironic-inspector
BMO ironic has no reason to run as root. Make it run as "ironic" user.
dnsmasq requires elevated capabiities. k8s is missing the feature of ambient capabilities, so it requires us to setcap the binaries with expected capabilities and container must be running with "allowPrivilegeEscalation: true" in the manifest to allow elevation.
Read the ambient capabilities KEP for more details: https://github.com/kubernetes/enhancements/blob/master/keps/sig-security/2763-ambient-capabilities/README.md
Most of the changed here are making runtime configuration possible by changing file and directory ownership from root:root to root:ironic and applying 775/664 perms to allow modification/creation of files.
=> make ironic-image runnable as non-root

Dockerfile, hack/shellcheck.sh, patch-image.sh, prepare-efi.sh, prepare-image.sh, scripts/configure-coreos-ipa, scripts/configure-httpd-ipa.sh, scripts/configure-ironic.sh, scripts/coreos-ipa-common.sh, scripts/ironic-common.sh, scripts/rundnsmasq, scripts/runhttpd, scripts/runironic, scripts/runironic-api, scripts/runironic-conductor, scripts/runironic-exporter, scripts/runironic-inspector, scripts/runlogwatch.sh, scripts/tls-common.sh
Add shellcheck. Fix all the shellcheck complaints, and make shell code consistent Bash.
Another PR in project-infra will activate the check for PRs.
Markdownlint is separated to its own PR #413
=> add shellcheck and fix complaints

Dockerfile, README.md, prepare-image.sh
Change the default method to install ironic software and its dependencies from source code instead of RPMs.
The "rpm" method is deprecated and it will be removed in the future.
=> Default installation from source

README.md, ironic-config/inspector.ipxe.j2, ironic-config/ironic.conf.j2, scripts/configure-ironic.sh, scripts/runhttpd
This update tracks a new environment variable, `IRONIC_IPA_COLLECTORS`, which is set to default to `default,extra-hardware,logs`, but can be overridden, and which is used to provide values to the kernel parameter `ipa-inspection-collectors`.
It seems that this value is used in two different places:
* By Ironic in `ironic.conf.j2`, which is configured with `configure-ironic.sh`
* By the file `inspector.ipxe` served by the web server and configured from `inspector.ipxe.j2` in `runhttpd`
To make this work, both of the template files have been updated and the scripts which call the `render_j2_config` command on those templates has had the variable exported and the default value added there.
These changes seem to be working locally as part of a Baremetal Operator deployment.
Closes: #414
=> Added IRONIC_IPA_COLLECTORS configuration option

patch-image.sh
metal3_daily_main_fullstack_building is failing with error 
`
/bin/patch-image.sh: line 16: git: command not found
`
ref to failed test: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_fullstack_building/187/consoleFull
Fix: install git-core in the patch-image.sh before git clone
=> Fixing patch-image.sh script for "$INSTALL_TYPE" == "source" 

README.md, ironic-config/ironic-python-agent.ign.j2, ironic-inspector-config/ironic-inspector.conf.j2, scripts/configure-ironic.sh, scripts/runhttpd
After https://github.com/metal3-io/baremetal-operator/pull/1297,
it is no longer needed. Upstream ramdisks do not support it.
=> Stop using extra-hardware by default

ironic-config/ironic.conf.j2
This PR addresses issue of occasionally missing IPA logs in the console logs during nodes inspection. The problem was identified as the absence of the kernel parameter "`systemd.journald.forward_to_console=yes`". The parameter was present when booting from `inspector.ipxe`, explaining the inconsistency. To resolve this, the PR adds the parameter to the relevant kernel `kernel_append_params`, ensuring consistent log forwarding.
=> 🐛 Ensure Consistent Capture of IPA Logs in Serial Console

scripts/ironic-common.sh
Seen this on Kind: the interface is listed as eth0@if4, but you actually
need to access it as eth0.
=> Account for interfaces ending with @something

prepare-image.sh
current-triple is no longer maintained, puppet-passed-ci has at least gone through some RDO packstack scenario ci jobs.
=> Switch from current-tripleo to puppet-passed-ci

scripts/ironic-common.sh
Provides more debugging info and can avoid situation where the pipe hides errors.
=> Use bash process substitution instead of pipe

configure-nonroot.sh
Otherwise, it cannot be created later if something is mounted under it.
=> Make sure /certs/ca is created in configure-nonroot

ironic-config/ironic.conf.j2, resources/sushy-tools/Dockerfile
This commit adds `enabled_firmware_interfaces` configuration option with current available options.
=> Support Firmware Interface

ironic-config/httpd.conf.j2
The ServerName value is not mandatory and it's not really needed as apache can get that from /etc/hosts.
Also this configuration will never work in an ipv6 environemnt as ipv6 ips are not allowed as values for ServerName.
=> Remove ServerName from httpd.conf

scripts/ironic-common.sh
This simplifies the case where PROVISIONING_IP is known but
the exact interface name is not.
=> Allow guessing PROVISIONING_INTERFACE by PROVISIONING_IP

scripts/auth-common.sh, scripts/configure-ironic.sh, scripts/runhttpd, scripts/runironic, scripts/runironic-inspector
To simplify future extensions and make the critical code easier to
review, move all credentials logic to a new script.
=> Consolidate the authentication code

ironic-config/ironic.conf.j2
We need to use either idrac-wsman or idrac-redfish, the plain idrac
(which are actually aliases for idrac-wsman) are going to be removed
very soon: https://review.opendev.org/c/openstack/ironic/+/902107
=> Stop using the deprecated 'idrac' interface aliases

resources/sushy-tools/Dockerfile, resources/sushy-tools/redfish-emulator.sh
Hardcoding :: makes it impossible to override the listen IP, which can
by handy in some testing scenarios.
=> sushy-tools: make listen interface customizable

resources/sushy-tools/Dockerfile
This will allow sushy-tools containers to use the nova driver, as well as the libvirt driver.
=> Add openstacksdk to sushy-tools container image

README.md
Add CLOMonitor badge to README as ironic-image is one of the included repos that is checked (starting tomorrow).
=> add clomonitor badge to README

ironic-config/ironic.conf.j2
Previously custom ironic ipxe template was taken into use in ironic config even when the TLS support was not enabled for the ironic-image.
This commit:
- Adds  a condition to exclude/include referencing custom ipxe template based on whether TLS is enabled for the ipxe.
=> add condition for ipxe_tls template usage

resources/sushy-tools/Dockerfile
[sushy-tools 1.1.0](https://review.opendev.org/c/openstack/releases/+/903515) has just been released. It contains new features and bugfixes ([changelog](https://opendev.org/openstack/sushy-tools/compare/1.0.1...1.1.0)).
=> Update sushy-tools to 1.1.0

scripts/tls-common.sh
The variables are confused there, breaking, for instance, vmedia TLS.
=> Fix invalid iPXE TLS variables

ironic-config/inspector.ipxe.j2
The Ironic inspector iPXE config, the kernel and ramdisk use IRONIC_IP which doesn't put brackets around IPv6 addresses. This causes the Host address to be malformed when iPXE sends a request. 
Fixes #
=> :bug: Ironic inspector iPXE address doesn't include brackets for IPv6 addresses

resources/sushy-tools/Dockerfile
It should reduce the final size of the image from 1.2GB to 500MB
=> 🌱 Use bookworm slim to build sushy-tools image

.github/workflows/build-images-action.yml
This PR changes the container build wf in accordance to the params change in https://jenkins.nordix.org/view/Metal3/job/metal3_ironic_container_image_building. With this the wf should trigger new builds not only to merged PRs, but also to git tags creation.
=> 🌱 Add tag trigger to images building wf

.github/workflows/build-images-action.yml, .github/workflows/pr-verifier.yaml
Cleanup GH actions, and move permissions from top-level to job-level. Restrict job running to the main repository.
This restores token permission score to 10/10.
/hold
until https://github.com/metal3-io/ip-address-manager/pull/408 is reviewed and merged as this is replication of that.
=> 🌱 reduce github actions permissions

README.md
Add OpenSSF Scorecard badge to README. It is checked by the CLOmonitor and lowers our score by not having it. We have worked to improve the scores, so we can display the score as well.
=> :book: add OpenSSF Scorecard badge to README

ironic-config/ironic.conf.j2
This parameter is about to change its default value from False to True.
Since we configure both managed and unmanaged inspection boots (see docs),
we can leave this option as False.
=> 🌱 Set require_managed_boot to False

.markdownlint-cli2.yaml, hack/markdownlint.sh
Switch markdownlint container to markdownlint-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass
=> :book: switch markdownlint container to markdownlint-cli2

README.md, ironic-config/inspector.ipxe.j2, ironic-config/ironic.conf.j2, scripts/configure-ironic.sh
This value is not specific to inspection, let alone its ironic-inspector
implementation. Rename to IRONIC_ENABLE_VLAN_INTERFACES. The old name is
still supported but deprecated.
=> 🌱 Rename IRONIC_INSPECTOR_VLAN_INTERFACES

resources/vbmc/Dockerfile
The tripleo repo has been archived as tripleo is not maintained anymore.
Let's switch to RDO repos for vbmc to avoid breakage.
=> :bug: Fix vbmc container build after tripleo deprecation

ironic-config/ironic.conf.j2, scripts/ironic-common.sh
Allow auto-discovery to be enabled with the built-in inspection.
=> ⚠️ Disable ironic-inspector by default

ironic-config/ironic.conf.j2, ironic-rpm-list, ironic-source-list
Both drivers (in case of idrac - its wsman implementation) has been
unmaintained for years, same for their underlying libraries ibmcclient [1]
and dracclient [2]. Ironic has deprecated them in the 2024.1 cycle.
Dell users should use idrac-redfish:// and idrac-virtualmedia:// instead.
iBMC users should try using the generic Redfish drivers and report any
bugs to the Ironic team and any standard compatibility problems directly
to Huawei.
[1] https://github.com/IamFive/python-ibmcclient
[2] https://opendev.org/openstack/python-dracclient
=> ⚠️ Remove ibmc and idrac drivers

resources/sushy-tools/Dockerfile
To be consistent with other Dockerfiles, and to allow easy replacement of the base image, add ARG BASE_IMAGE to sushy-tools Dockerfile.
=> 🌱 add ARG BASE_IMAGE to sushy-tools Dockerfile

resources/vbmc/Dockerfile
Switch the virtualbmc image to python base image based on bookworm to reduce its size from 400MB to 290MB
=> :seedling: Build virtualbmc image using python image

configure-nonroot.sh, scripts/configure-ironic.sh, scripts/ironic-probe.j2
This change is the first step towards https://github.com/metal3-io/baremetal-operator/issues/1528.
Through these scripts, we can decouple the validation logic from
the pod definition and provide more sophisticated tests in the future.
Right now, the same curl command is used (modulo supporting all variants
of deploying Ironic).
=> ✨ Provide scripts to be used as liveness/readiness probes

scripts/auth-common.sh
Security baselines such as CIS do not recommend using secrets as environment variables, but using files instead. Therefore, the IRONIC_HTPASSWD and INSPECTOR_HTPASSWD will now be populated from files instead of environment variables.
=> 🐛 Stop reading ironic and inspector HTPASSWD from environment variables

scripts/auth-common.sh
Update the method of reading ironic htpasswd username and password from file, to make it less sensitive to error whether or not the file ends in newline.
=> 🌱 Fix error in reading ironic htpasswd from file

ironic-config/ironic.conf.j2
Loading the "flat" network interfaces causes a confusing warnings about
unset cleaning_network parameter. Just disable it.
Sort the options in the configuration.
=> 🐛 Disable unused network interfaces

scripts/auth-common.sh
This PR reverts #482 and #498, because it is not secure to mount the ironic username and password as plain text files into
ironic-image. The PR adds the ability to mount the ironic htpasswd as a file (to introduce a better way than just using environment variable for this purpose).
=> 🌱 Read Ironic htpasswd from file or environment variable

hack/shellcheck.sh
Make shellcheck consider only files.
If branch name ended with .sh or .sh/something, it was found on the filesystem as something ending with .sh, and shellcheck picked it up, and linting failed obviously.
=> 🌱 shellcheck only files

.github/workflows/build-images-action.yml
Ironic-image build locally, with a fast disk, fast CPU, and fast net takes 500-600s, depending on pre-pulls, repository speeds etc. New cloud has none of those reliably, so it times out at 1000s far too often. Also scheduling time is considered when images are built in Jenkins, and often scheduling takes a long time. Thanks to #505  we get notifications of these failures now.
- Ironic image: 1000s -> 3600s (build time 500-600s, less than 2x safety)
- Sushy-tools: keep 1000s (build time 150s, 6x safety)
- VMBC: keep 1000s (build time 100s, 10x safety)
I will cherry-pick this to release branches as well.
=> 🌱 increase ironic-image build timeout to 3600s

ironic-config/httpd.conf.j2
The current `Listen` directive does not work on systems that have ipv6 disabled. The Apache Listen directive supports `Listen <port>` syntax at which point it seems to be able to listen correctly on both dual stack and ipv4 only systems. See https://httpd.apache.org/docs/2.4/bind.html for more details.
Fixes #531
=> 🐛 Update httpd.conf.j2 

prepare-image.sh
We don't really need it in the final image
=> :seedling: Remove dnf config-manager after its use

Dockerfile
This is a tentative to make ipxe more close to the current version
and include some improvements and bug fixes.
As a first step we build and install ipxe using a commit hash,
as no stable versions have been released since December 2020.
We point the ipxe commit hash to [1] from November 2021, so
roughly a year of changes is included.
To see the complete list of changes run:
`git log --pretty=oneline 988d2c1..9062544`
from a local clone of the ipxe repository.
In general the changes included between the stable 1.21.1
version and the current chosen hash improve compatibility
with recent gcc and build libraries, while fixing
numerous bugs.
This change also introduce a build arg to allow choosing
the ipxe commit hash at container build time.
[1] …
=> :warning: Update ipxe version

prepare-image.sh
We don't really need to keep pip cache as we don't install more packages with pip after the initial build.
It should reduce the size of the final image of about 50MB.
=> :seedling: Disable pip cache

.github/workflows/build-images-action.yml
The syntax error in build images workflow caused all jobs to fail. These could probably be automatically caught in the future
=> 🌱 Fix syntax in build images github workflow

ironic-config/ironic.conf.j2, scripts/configure-ironic.sh
If FIPS is enabled in the hosts we should also run IPA in FIPS mode. It is possible to enable FIPS directly at kernel level using the fips option, determining the FIPS status for example from the cryptographic module and specifically the
/proc/sys/crypto/fips_enabled file; if the file contains 1 then the system is in FIPS mode, if it contains 0 the FIPS algorithms are disabled.
Therefore the value of the fips kernel option is 0 (default) if FIPS is disabled, or 1 if enabled.
=> :sparkles: Enable FIPS mode for IPA if system is in FIPS mode

resources/sushy-tools/Dockerfile
Bump sushy-tools version to the latest v1.3.0
https://opendev.org/openstack/sushy-tools/releases/tag/1.3.0
=> 🌱 Bump default sushy-tools version to 1.3.0

ironic-source-list
Workaround to unblock the CI.
This commit:
- Pins the Ironic source to a WIP upstream gerrit change that resolves a regression introduced by a recent change.
=> :bug: Pin ironic source

ironic-source-list
This reverts commit 9443d08bdda79ad3683fe887c1cc1dcd4e2efabc.
Revert temporary fix, when the [real bugfix](https://review.opendev.org/c/openstack/ironic/+/928885) has landed in Ironic's repository.
/hold
=> 🐛 Revert "pin ironic source"

ironic-config/ironic.conf.j2
Enable interface to allow UefiHttp boot.
Design Doc
https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/uefi-http-boot.md
=> ✨ Enable redfish-https boot interface

scripts/runlogwatch.sh
Use inotifywait instead of an infinite loop.
Fixes #547
=> 🐛Fix CPU burning on ironic-log-watch when no ramdisk file is present

scripts/ironic-common.sh
In case of SQLite implementation Ironic container fails to restart. create_schema will be called only when required.
fixes #562
=> 🐛SQLite: fix Ironic container restarting issue

.github/workflows/pr-verifier.yaml
Reuse PR verifier workflow from project-infra, so it is easier to maintain in a single place and reduces number of dependabot bump PRs targeting Github Actions, creating less noise.
=> :seedling: Reuse PR verifier wf from project-infra

prepare-image.sh
Usually the setuptools installed by the system is stable but a bit too old compared to the packages we use for ironic, so pinning a more recent version helps avoiding errors and incompatibilities.
(cherry picked from commit 82692ba7683ec1d48a67aaaaf6d8bf5496177c1d)
=> :bug: Pin setuptools during image build

Dockerfile
This is yet another tentative to make ipxe more close to the current version and include some improvements and bug fixes.
We point the ipxe commit hash to [1] from December 2022, so roughly a year of changes is included.
To see the complete list of changes run:
`git log --pretty=oneline 9062544..714753`
from a local clone of the ipxe repository.
In general the changes included between the old hash and and the current chosen hash improve compatibility
with recent gcc and build libraries, while fixing
numerous bugs.
This is a follow-up to https://github.com/metal3-io/ironic-image/commit/bd9319c91d75dd4e99efe6027de056d1187f9546
[1] https://github.com/ipxe/ipxe/commit/7147532c3fbf9a7061e74549f6f920a91ca9a80d
=> :warning: Update ipxe version to December 2022

Dockerfile
This is yet another tentative to make ipxe more close to the current version and include some improvements and bug fixes.
We point the ipxe commit hash to [1] from December 2023, so roughly a year of changes is included.
To see the complete list of changes run:
`git log --pretty=oneline 714753..119c41`
from a local clone of the ipxe repository.
In general the changes included between the old hash and and the current chosen hash improve compatibility
with recent gcc and build libraries, while fixing
numerous bugs.
This is a follow-up to https://github.com/metal3-io/ironic-image/commit/7c342825e30545c7ae0e6762100b2227e4030dea
[1] https://github.com/ipxe/ipxe/commit/119c415ee47aaef2717104fea493377aa9a65874
=> :warning: Update ipxe version to December 2023

Dockerfile, prepare-image.sh
This commit:
- Provides a default value for the UPPER_CONSTRAINT docker file argument
- Changes the prepare-image.sh logic to check the actual size of the upper constraint file and not the presence of it.
Background of this change is that it has been noticed that on release branches during image building the "pinned" upper constraint file is not picked up rather pulled from upstream OpenStack because of a lack of default argument value during image building.
=> 🐛 improve upper constraints handling

Dockerfile, prepare-image.sh
This commit:
- Provides a default value for the UPPER_CONSTRAINT docker file argument
- Changes the prepare-image.sh logic to check the actual size of the upper constraint file and not the presence of it.
Background of this change is that it has been noticed that on release branches during image building the "pinned" upper constraint file is not picked up rather pulled from upstream OpenStack because of a lack of default argument value during image building.
=> :bug: improve upper constraints handling

Dockerfile
This is yet another tentative to make ipxe more close to the current version and include some improvements and bug fixes.
We point the ipxe commit hash to [1] from May 2024, so roughly 6 months of changes are included.
To see the complete list of changes run:
`git log --pretty=oneline 119c41..e965f17`
from a local clone of the ipxe repository.
In general the changes included between the old hash and the current chosen hash improve compatibility
with recent gcc and build libraries, while fixing
numerous bugs.
On a side note, this is the minimum commit required to build ipxe on CentOS Stream 10.
This is a follow up to https://github.com/metal3-io/ironic-image/commit/4955fbbbb3283f9a12e8e63d1326d666fdda79b1
[1] https://github.com/ipxe/ipxe/commit/e965f179e1654103eca33feed7a9cc4c51d91be6
=> :warning: Update ipxe version to May 2024

README.md
Update build status badges to point to correct e2e tests.
=> :book: fix broken build status badges

.github/workflows/build-images-action.yml, docs/releasing.md, resources/ironic-client/Dockerfile, resources/ironic-client/README.md, resources/ironic-client/scripts/openstack
Relocate ironic-client image from ironic-client repo, which will be archived.
Ref: https://github.com/metal3-io/ironic-client/issues/30
=> :sparkles: relocate ironic-client to this repository

ironic-config/ironic.conf.j2
This PR:
- Implements the support for disabling the deep_image_inspection via environment variable.
This new functionality is needed because e.g right now the Ironic&IPA has issues running deep image inspection on e.g. live-iso images.
=> :sparkles: Make deep image inspection configurable

docs/releasing.md
Add prior art PRs to fixing build badges, as well as prior art link to 27.0.0 release, where we first time added extra information about upstream Ironic changelog and full commit range link.
=> :book: add more prior art to releasing.md

main-packages-list.txt, prepare-image.sh, scripts/runhttpd, scripts/runironic, scripts/runlogwatch.sh
The inotify-tools last release is from september 2023
and last update in the repo is 7 months old (May 2024).
The inotify-tools package is not present in the EPEL10 repo
anymore while python3-inotify is in a native repository.
This change allows us to remove dependency from EPEL entirely.
Closes https://github.com/metal3-io/ironic-image/issues/605
=> :seedling: Use pynotify instead of inotify-tools

Dockerfile, README.md, docs/releasing.md, ironic-packages-list, prepare-image.sh
The ironic source code does not depend from ironic-lib anymore.
For more info please check [1]
[1] https://opendev.org/openstack/ironic/commit/74d239d4ebfde3e66d838c0cb74992bae0f7c00c
=> :warning: Remove ironic-lib dependency

resources/ironic-client/Dockerfile
This is where python3.9 has been installed
Fixes: #609
=> 🐛 Install python-ironicclient in /usr/local

scripts/ironic-common.sh
The grep -q closes input pipe immediately if any match is found, while the command on the left side will exit with SIGPIPE when it tries to write to a closed pipe, causing the Metal3 Pod to get stuck in CrashLoopBackOff sometimes.
**Which issue(s) this PR fixes**:
Fixes #611
=> 🐛 Drop quiet option of grep to avoid race condition with pipefail

.github/workflows/irso-functional.yml, hack/ci-e2e.sh
=> 🌱 Run the IrSO functional job on ironic-images changes

.github/dependabot.yml
Now that we have workflows in this repository, let's add Dependabot config to keep them up to date. Assigning an individual weekday for this repo, and interval of one month.
=> :seedling: add dependabot configuration for actions

scripts/auth-common.sh, scripts/configure-ironic.sh
It's probably not a great idea to allow users to easily access JSON RPC,
so a different set of credentials is useful.
Also allow the secret to be mounted directly without the convoluted
auth-config format (which is an ini file in reality). Deprecate
the auth-config approach (JSON RPC is the last instance where it's
used).
=> ✨ Allow independent credentials for JSON RPC

scripts/runlogwatch.sh
Use correct values for read command, and remove colors from
output.
a pyinotify event looks like this:
\<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 \>
by default the output contains colorize text that is
interpreted literally by variable conversion in the
tar command, so not only we have to parse it, but
we also need to get just raw format output.
Fixes #630
=> :bug: Fix runlogwatch script

scripts/configure-ironic.sh
This removes the faulty NUMPROC processor count detection logic from the configure-ironic.sh. It used to limit CPU count to 4, but the "fixed" version made it a MINIMUM of 4.
This detection has now been merged on the ironic api side, so we can remote the note + the faulty logic, and just leave the minimal env var there. 0 means ironic will run its autodetection logic and set maximum of 4 cores.
This fix has been merged on the Ironic side already in 2020, so we can backport this to all branches we have.
Fixes: #635
=> :bug: remove faulty NUMPROC logic

README.md, scripts/auth-common.sh, scripts/configure-ironic.sh
Passing a password in clear text is an obviously bad idea. Add support
for mounting a secret and deprecate the clear text approach.
This change also makes it a fatal error to not pass the password.
Our mariadb-image does not support empty passwords anyway, and we should
not rely on anyone actually using "change_me" without realizing it.
=> ⚠️ Deprecate passing MARIADB_PASSWORD in favour of mounting a secret

README.md, prepare-efi.sh
This simple change allows us to build ironic containers using
CS10 base images, adding that as supported OS.
This has been tested locally and in CI.
related issue https://github.com/metal3-io/ironic-image/issues/529
=> :sparkles: Install shim-pkg explicitly and add support for CentOS Stream 10

README.md, ironic-config/ironic.conf.j2, scripts/configure-ironic.sh, scripts/ironic-common.sh, scripts/runironic
Previously, it defaulted to true for a split API/conductor deployment,
but this mode is no longer supported. Most deployments use a single
Ironic process and SQLite as a backend.
Update README with the relevant parameters.
=> ⚠️ Set IRONIC_USE_MARIADB to false by default in all cases

scripts/rundatabase-upgrade, scripts/runironic, scripts/runonline-data-migrations
The new entrypoints rundatabase-upgrade and runonline-data-migrations are
designed to be run as a Job every time Ironic is upgraded. See also:
https://docs.openstack.org/ironic/latest/admin/upgrade-guide.html
=> ✨ Add scripts to run database upgrades and online migrations

resources/sushy-tools/Dockerfile
We release sushy-tools 2.0.0 last week, let's update the version we use in Metal3
https://review.opendev.org/c/openstack/releases/+/943234
=> 🌱  Update sushy-tools to 2.0.0

.github/workflows/build-images-action.yml
This reverts commit d5346788611090b94b310e05bd81fff8592dea84 (ie. PR #646)
Newly added syntax breaks the builds for entire repo. We have 5 images built here, so I'm reverting this and we'll reintroduce the patch.
Fixes: #650
=> :bug: Revert "Add build ironic-image with CentOS Stream 10"

ironic-config/ironic.conf.j2, scripts/ironic-common.sh, scripts/rundatabase-upgrade, scripts/runhttpd, scripts/runonline-data-migrations
This PR:
- Removes unused IPXE_CONF_DIR variable
- Removes unjustified line break
- Configures the ironic temp_dir to use env var instead of hard coded value
- Make the recently added online data migration feature compatible with custom config paths
- Make the recently added rundatabase-upgrade compatible with custom config paths
This PR is a followup to https://github.com/metal3-io/ironic-image/pull/634 and https://github.com/metal3-io/ironic-image/pull/623 with the aim to harmonize the the new feature sets and fix a few nits.
=> :bug: harmonize custom config/data paths and db data migration

scripts/tls-common.sh
With a read-only root filesystem and no TLS, this action fails.
Add a conditional mkdir in the only place where we actually try
to write to one location.
=> 🐛 Stop doing mkdir on /certs subdirectories

Dockerfile, README.md, ironic-config/httpd.conf.j2, ironic-config/ironic.conf.j2, scripts/rundnsmasq, scripts/runhttpd
Unfortunately, a lot of code in Ironic ignores the tempdir
configuration. Even worse, the default value for this option relies on
having a writable /tmp, which makes the current approach not functional
without mounting an emptyDir to /tmp. But if an emptyDir is mounted to
/tmp, we lose access to all the template files stored there.
This change uses a new directory /templates as a source for files that
needs copying/templating in runtime.
Also fix usage of /var/tmp in httpd.conf.
Document the requirements.
=> 🐛 Do not use /tmp as a source directory for the image

.github/workflows/build-images-action.yml, README.md
This (hopefully) enables multiarch builds on the sushy-tools container image.
**Which issue(s) this PR fixes**:
Fixes #615 
Also, see https://github.com/metal3-io/project-infra/pull/960 as required for this to work.
=> 🌱 Enables sushy-tool image multiarch builds

.github/workflows/irso-functional.yml, hack/ci-e2e.sh
This change largely mirrors the changes to IrSO CI.
Go back to using `minikube image load` with a tarball.
=> 🌱 Use a multi-node cluster in functional tests 

ironic-config/ironic.conf.j2, scripts/runhttpd
There is no need to go through the HTTP server for it: it is only used
locally by Ironic itself.
=> 🌱 Use bootloader through a local file link

scripts/runlogwatch.sh
Currently, the file listing is sent to stderr, while files themselves
are sent to stdout. Then the two streams are merged in the resulting
CI report. However, they are not guaranteed to be 100% synchronized,
which results in file names appearing in the middle of log lines.
They are also neither human- nor machine-friendly.
Here I'm switching from extracting all files using -Ov to listing files
first and extracting them one by one.
I'm also adding extra new lines before each file to make the output more
readable.
=> 🐛 Extract files one-by-one in logwatch

tools/parse-ramdisk-logs.py
The new script can be invoked like this:
```
./tools/parse-ramdisk-logs.py ramdisk-logs.txt /path/to/destination
```
and will extract everything in the following directory structure:
```
├── namespace~hostname
│   ├── cleaning-2025-05-06-10-38-12
│   │   ├── dmesg
│   │   ├── ip_addr
│   │   ├── journal
│   │   ├── lsblk
│   │   ├── lsblk-full
│   │   ├── lshw
│   │   ├── mdstat
│   │   ├── mount
│   │   ├── multipath
│   │   ├── parted
│   │   ├── udev
│   │   │   ├── loop0
│   │   │   ├── loop1
│   │   │   ├── sda
│   │   │   └── sr0
│   │   └── var
│   │       └── log
│   │           └── ironic-python-agent.log
│   ├── deploy-2025-05-06-10-39-31
(etc)
```
The ramdisk logs **must** be created by ironic-image with this change: https://github.com/metal3-io/ironic-image/pull/673 …
=> 🌱 Add a helper script to parse ramdisk logs

ironic-config/ironic.conf.j2
The fix for OSSA-2025-001 introduces a new option that limits which
paths are allowed for file:// URLs. The default value already contains
the paths that Metal3 uses, but it will change in the future.
=> 🐛 OSSA-2025-001: set file_url_allowed_paths to what Metal3 uses

ironic-packages-list
The sushy-oem-idrac code is now included in sushy
=> :warning: Do not install separate sushy-oem-idrac

resources/ironic-client/Dockerfile, resources/sushy-tools/Dockerfile, resources/vbmc/Dockerfile
Moving ironicclient, sushy-tools and vbmc to Python 3.12
=> :warning: Use Python 3.12 for resources images

.github/workflows/release.yaml, Makefile, docs/releasing.md, hack/tools/go.mod, hack/tools/go.sum, hack/tools/release/notes.go
Add new changelog based release creation automation and update release documentation.
Note: ironic-image is not Go-centric repo, so let's not add all the bells and whistles related to the release note generator Go code (linters etc) as we plan to make it reusable from project-infra to avoid having 10 copies of the code for ever to maintain.
=> :sparkles: add new release automation and documentation

.github/workflows/release.yaml, docs/releasing.md
Account for ironic_cs10 image in release job and use the correct image names as well.
Fix the documentation related to this too.
=> :bug: fix release image building

README.md, ironic-config/ironic.conf.j2, scripts/configure-ironic.sh
These variables have the same meaning as on BMO and configure the
default URL's for IPA.
=> ✨ Support DEPLOY_KERNEL_URL and DEPLOY_RAMDISK_URL

scripts/configure-ironic.sh
Ironic's security checks don't recognize //shared as a valid prefix.
Follow-up to 315acdab32f296f850cd3961a5e0fde095567659.
=> 🐛 Remove extra slash from deploy kernel/ramdisk paths

ironic-config/dnsmasq.conf.j2
The current dnsmasq configuration caused dnsmasq container to stop due to wrong configuration in IPv6 only environment. This PR fixes that issue and also removes duplicate block from the configuration.
Fixes #614
=> :bug: Fix dnsmasq config ipv6 issues

ironic-config/dnsmasq.conf.j2
Reverts metal3-io/ironic-image#708
After testing this patch on an actual ipv6 deployment, we've verified that this change breaks dnsmasq and ip assignment
The router option does work as expected instead
```
dnsmasq: started, version 2.85 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth cryptohash DNSSEC loop-detect inotify dumpfile
dnsmasq-dhcp: DHCPv6, IP range fd00:1101::a -- fd00:1101::ffff:ffff:ffff:fffe, lease time 1d
dnsmasq-dhcp: router advertisement on fd00:1101::
dnsmasq-dhcp: RTR-ADVERT(enp1s0) fd00:1101::
dnsmasq-dhcp: IPv6 router advertisement enabled
dnsmasq-dhcp: DHCP, sockets bound exclusively to interface enp1s0
```
=> :bug: Revert "Fix dnsmasq config ipv6 issues"

OWNERS, OWNERS_ALIASES
Derek is no longer working in our team, so removing him.
Adam has contributed significant features to ironic-image, and has been
reviewing both it and IrSO consistently.
We should probably consider more promotions, but at least the gap is
covered.
=> 🌱 Approvers: remove Derek, add Adam

ironic-config/httpd-modules.conf
mod_proxy_ajp is only necessary for some Java applications.
mod_proxy_balancer is for connecting to several backends.
=> 🐛 Disable unused httpd mod_proxy extensions

prepare-image.sh, scripts/runlogwatch.sh, scripts/tls-common.sh
Watchdog comes with a shell utility script, watchmedo, that can perfectly replace pyinotify, and it works natively with Python 3.12
We drop pyinotify in favor of watchdog and convert the scripts to use watchmedo.
Fixes #715
=> :warning: Use watchdog to monitor logs and certificate changes

prepare-efi.sh
During efi build, remove the shim package but not its
dependencies to avoid conflict between architectures.
This has been tested locally with both CS9 and CS10
base images.
=> :bug: Fix CentOS Stream 10 build

.github/workflows/irso-functional.yml
We are missing "edited" from IRSO functional job triggers.
This needs to be cherry-picked to 30.0 and 31.0 branches as well.
/cherry-pick release-30.0
/cherry-pick release-31.0
=> :seedling: add edited as irso functional trigger

.github/workflows/irso-functional.yml
See [BMO 2599](https://github.com/metal3-io/baremetal-operator/pull/2599) for reference.
/hold
To be merged when all repos show green with new workers.
=> :seedling: use new cncf oracle gh runners

ironic-config/ironic.conf.j2
Reverts metal3-io/ironic-image#756
This is breaking live-ISO tests in BMO e2e
=> :seedling: Revert "Use the shared directory to store master iso images on ironic-conductor node"

.github/workflows/ironic-image-build-pr.yml
Test if ironic-image can be built using both CS9 and CS10 before running e2e tests.
=> :seedling: Add build ironic-image workflow on PRs
